[project]
name = "belgian_dwellings"
version = "0.1.0"
dynamic = ["dependencies", "optional-dependencies"]
requires-python = "<3.14"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt", "requirements_submodules.txt"]}

[tool.setuptools.packages]
find = {}